### ISSUE TITLE
Don't auto create devices by default

### ISSUE THREAD

**Issue by indigo-jay** [IndigoDomotics/Hue-Lights-Indigo-plugin#7]
I'm not sure if it's doing it by default or if it's only creating the "Hue New Devices" folder, but neither should happen unless the user asks for the devices to be created. Users get very confused when new stuff that they didn't explicitly create just show up.

**Comment by kw123** [comment]
Yes it does that. 

I can change it to only create that folder if the menu item create  all new devices is executed.  Good feedback 


Karo
